openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

# consumes:
#   - "application/json"
# produces:
#   - "application/json"    

servers:
  - url: "/api"

paths:
  /people:
    get:
      operationId: "people.read_all"
      tags:
        - "People"
      summary: "Read the list of people"
      responses:
        "200":
          description: "Successfully read people list" 
    post:
      operationId: "people.create"
      tags:
        - People
      summary: "Create a person"
      requestBody:
        description: "Person to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "person"
              $ref: "#/components/schemas/Person"
      responses:
        "201":
          description: "Successfully created person"        
  /people/{lastname}:
    get:
      operationId: "people.read_one"
      tags:
        - People
      summary: "Read one person"
      parameters:
        - $ref: "#/components/parameters/lastname"
      responses:
        "200":
          description: "Succesfully read person"    
    put:
      tags:
        - People
      operationId: "people.update"
      summary: "Update a person"
      parameters:
        - $ref: "#components/parameters/lastname"
      responses:
        "200":
          description: "Successfully updated person"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "person"
              $ref: "#/components/schemas/Person" 
    delete:
      tags:
        - People
      operationId: "people.delete"
      summary: "Delete a person"
      parameters:
        - $ref: "#/components/parameters/lastname"
      responses:
        "204":
          description: "Successfully deleted person"    

components:
  schemas:
    Person:
      type: "object"
      required:
        - lastname
      properties:
        firstname:
          type: "string"
        lastname:
          type: "string"      
  parameters:
    lastname:
      name: "lastname"
      description: "Last name of the person to get"
      in: path
      required: True
      schema:
        type: "string"

